services:
  backend:
    build:
      context: .  # Root directory as context
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/data/clinic_schedule.db:/app/data/clinic_schedule.db

  frontend:
    build:
      context: .  # Root directory as context
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
