services:
  backend:
    build:
      context: .  # Root directory as context
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/data/clinic_schedule.db:/app/data/clinic_schedule.db

  frontend:
      build:
        context: .
        dockerfile: frontend/Dockerfile
      ports:
        - "5173:5173"
      environment:
        - NODE_ENV=development
      stdin_open: true
      tty: true
