services:
  backend:
    build:
      context: ./  # Corrected to point to the current folder
      dockerfile: ./Dockerfile
    env_file:
      - /.env  # Ensure this points to the correct .env location
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data/clinic_schedule.db:/app/data/clinic_schedule.db
      
