#Config for my_efimeria
ONLINE_SPREADSHEET_ID: 1W7Zcz75bw3usVNZCfX0HAASmMuzExC-5DqDPedfjX3k
ONLINE_SREADSHEET_INPUT_SHEET_NAME: Input
ONLINE_SREADSHEET_OUTPUT_SHEET_NAME: ExclusionList 
ONLINE_SREADSHEET_EXCLUSION_SHEET_NAME: Output



